### ISSUE TITLE
Error when calling module

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-wttam#4]
filemtime(): stat failed for …/modules_v4/huhwt-wttam/resources/css/cceTa.css …/app/Module/ModuleCustomTrait.php:154
#0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/Module/ModuleCustomTrait.php(154): filemtime()
#2 …/modules_v4/huhwt-wttam/TAMaction.php(245): HuHwt\WebtreesMods\TAMchart\TAMaction->assetUrl()
#3 …/app/Http/RequestHandlers/ModuleAction.php(85): HuHwt\WebtreesMods\TAMchart\TAMaction->getTAMAction()
#4 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()

**Comment by huhwt** [comment]
There was missing CSS, is added now ...
