### ISSUE TITLE
2.1.7.0.4 - Error on Execute an action on records in the clippings cart with CCE

### ISSUE THREAD

**Issue by TheDutchJewel** [huhwt/huhwt-wttam#5]
When using the function `Execute an action on records in the clippings cart` in the huhwt-cce module:
![afbeelding](https://user-images.githubusercontent.com/46184729/205258184-8ed699ed-44fc-48d1-85fc-88e4b0d862c9.png)

I get this error when using TAM:
![afbeelding](https://user-images.githubusercontent.com/46184729/205257600-3ba36284-5a75-4242-b0d7-a9084e076cc3.png)

and this one when using Lineage:
![afbeelding](https://user-images.githubusercontent.com/46184729/205258345-1cbb0ee9-f501-43a8-ae2b-8bf1d3964090.png)

Tested on Win10 Home 22H2 and XAMPP 8.0.25 with:
- webtrees 2.1.9
- huhwt-wttam 2.1.7.0.4
- huhwt-cce 2.1.7.1

**Comment by huhwt** [comment]
With PHP 8.0.x I have not tested it ... But for me it runs cleanly now in this configuration:
PHP 8.1.12
webtrees 2.1.12
huhwt-lin 2.1.7.1
huhwt-tam 2.1.7.0.2
huhwt-cce 2.1.7.1
Regardless of PHP and webtrees version (ran cleanly also with PHP 7.29 and webtrees 2.1.7), I recommend deleting the collection container after upgrading from huhwt versions < 2.1.7.x (can also be done from the other ClippingsCart modules). The error indicates problems with the transfer of information from huhwt-cce and huhwt-lin or -tam, there were changes in previous releases.

**Comment by TheDutchJewel** [comment]
> I recommend deleting the collection container after upgrading from huhwt versions < 2.1.7.x (can also be done from the other ClippingsCart modules). 

Done, problem solved. Thank you!
